### ISSUE TITLE
community contributions ready

### ISSUE THREAD

**Issue by Enalmada** [thangngoc89/bs-ant-design#11]
Thank you for this and the blog post.  I notice that [andresrgz/bs-ant-design](https://github.com/andresrgz/bs-ant-design) has added some components and there is a Card component pull request.  I would like to contribute some missing things in the near future too.  Could you get those existing community contributions into master to keep the momentum on this amazing effort going.

**Comment by thangngoc89** [comment]
Hello, I added @andresrgz as a committer for this repository. He's probably busy with his work but I believe he'll merge the change back here.

**Comment by Enalmada** [comment]
Excellent!  Thanks so much for making ant design bindings that don't fail at runtime.
