### ISSUE TITLE
bs-and

### ISSUE THREAD

**Issue by Enalmada** [thangngoc89/bs-ant-design#12]
Would it make sense to take the bindings in bs-antd and override that with the improved bindings made available here?  Would combining both somehow give the community better overall antd support than each individually?  I am just getting up to speed on this but it seems like bs-antd has full coverage but some of the interfaces have an issue that you have identified but I am curious if it is generally worth trying to fall back to bs-antd if a component doesn't exist yet here.  Or is it better if I just create it following the pattern you have setup here and just pretend that bs-antd doesn't exist.

**Comment by thangngoc89** [comment]
@Enalmada I tried what you are describing a while back but I didn't work quite well. Because of the problem I described in the blog post. Many components just silently failed on runtime so I would rather have less components then full coverage but randomly fails component

**Comment by Enalmada** [comment]
I totally agree.  Thanks for the extra background.  Now I know the best way to proceed is to follow the pattern you have setup when I need a component without a binding yet.
