### ISSUE TITLE
Releasing a new package version on npm?

### ISSUE THREAD

**Issue by bnoguchi** [thangngoc89/bs-ant-design#13]
Is the current master snapshot ready for another release to npm?

**Comment by luisfcofv** [comment]
It is, let's bump a major version @thangngoc89

**Comment by thangngoc89** [comment]
@luisfcofv what is your npm handle? I'll add you to maintainer list

**Comment by luisfcofv** [comment]
Same. `luisfcofv`

**Comment by thangngoc89** [comment]
@luisfcofv Done

**Comment by luisfcofv** [comment]
Great, I will make a release soon (not on my computer at the moment)

**Comment by thangngoc89** [comment]
@luisfcofv Thank you very much

**Comment by luisfcofv** [comment]
v2.0.0 is live. I'm closing this issue.
