### ISSUE TITLE
Any plans to update this to support hooks?

### ISSUE THREAD

**Issue by anisjonischkeit** [thangngoc89/bs-ant-design#27]
Just wondering if this is still being maintained and whether the hooks update is planned for the near future.

**Comment by JakubMarkiewicz** [comment]
@anisjonischkeit i'm currently rewriting fork of @enalmada fork to jsx3. Will probably make a PR to forked repo when I clean my code.
Working jsx3 components (not everything bust most things) are here https://github.com/JakubMarkiewicz/bs-ant-design/tree/jsx3. Notice there may be errors, i just convert them to jsx3 when i need specific component, didn't do much tests

**Comment by thangngoc89** [comment]
@anisjonischkeit @JakubMarkiewicz I don't use antd anymore so I gave permission to @luisfcofv and @andresrgz for maintaining it. I would be happy to transfer it to reason-community so this won't die

**Comment by luisfcofv** [comment]
I’m sorry, my team moved away from antd a few months ago, so we aren’t
maintain it anymore. Please transfer it if that will keep it alive.

**Comment by anisjonischkeit** [comment]
No worries :). Thanks for pointing out your fork @JakubMarkiewicz. Might be worth making @Enalmada's fork the main repo or if he doesn't want to maintain it moving it to reason-community since it looks like the fork that is the furthest along.

**Comment by andresrgz** [comment]
@thangngoc89 I also have moved onto different projects and I'm no longer using anything related to Reason or Antd anymore. Sorry about that, feel free to transfer it to the reason-community.

**Comment by Enalmada** [comment]
@thangngoc89 Give me github and npm maintainer permissions and I will help (will talk transfer ownership to me once I get my branch merged back in).  I changed jobs am not using it right now but would like to come back to it soon and willing to facilitate community contributions until I can come back professionally.  Until then I will use it on my sample project: https://github.com/Enalmada/next-reason-boilerplate

@JakubMarkiewicz The jsx3 effort looks interesting!  Please do a PR when you can.  Don't wait till it is perfect...in retrospect I should have just merged enalmada in here long ago before I switched jobs and got distracted.  I got demotivated by this issue https://github.com/thangngoc89/bs-ant-design/issues/25.  Does your jsx3 happen to work on latest antd and able to close that ticket once merged?  Once the jsx3 is merged in to enalmada branch I will get it merged here.

**Comment by JakubMarkiewicz** [comment]
@Enalmada Great, it should be ready in a few days, probably with some example app (in monorepo) for tests since it's not a lot of work.
I'm using latest ant 3.16.6 and it works great. I saw this issue a while ago but totally forgot about it

**Comment by Enalmada** [comment]
Thanks to @JakubMarkiewicz there is a jsx3 release published under `bs-ant-design-alt@2.0.0-alpha.1`.  If you are able to contribute:
* try it out and push fixes
* merge anything new here since branch into there

**Comment by david** [comment]
@thangngoc89 @Enalmada @JakubMarkiewicz any news about an official maintained version of this package? I'd be happy to help, if needed.

Also, @thangngoc89, if I may ask, did you move away from antd because you didn't need it anymore, or did you move to a different toolkit? If the latter, would it be to much trouble to talk a bit about the flaws you saw with antd?

**Comment by david** [comment]
@luisfcofv if you could talk a bit about what led your team to move away from antd I'd appreciate it too (if @thangngoc89 doesn't mind me hijacking this thread a bit). Antd is currently my favorite toolkit, but I appreciate hearing about other people's experiences.

**Comment by thangngoc89** [comment]
@david hey. The reason I moved away from this toolkit is because of its styling options. It affects the whole application with global styling and it's very hard to change the styling. (I need to use `!important` everywhere). 

Furthermore, I don't think manually maintain a big libraries like this is the best course of actions. I'd rather invest in automatic solution (like with bs-material-ui) once and be done with it.
